version: '3'
services:
  app:
    container_name: movie_app
    build: .
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes: 
      - .:/code
    env_file: 
      - .env
    entrypoint: ["sh", "./start.sh"]